[package]
name = "lohdb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
crossbeam = { version = "0.8", features = ["crossbeam-channel"] }
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.8"